---
format:
  docx:
    reference-doc: membership_reference_style.docx
execute:
  echo: false
  warning: false
  message: false
editor_options: 
  chunk_output_type: console
  
---

<!-- ::: {.landscape} -->

```{r}

library(RSQLite)
library(data.table)
library(readxl)
library(zoo)
library(lubridate)
library(glue)
library(jsonlite)
library(XLConnect)
library(openxlsx)
library(reticulate)
library(english)
library(multicool)
library(knitr)

library(here)

invisible(
  lapply(list.files(here("R"), full.names = TRUE),
         source
  )
)


if(!exists("conn")) {
  conn <- dbConnect(RSQLite::SQLite(), here("../3_data_derived/all_results.sqlite"))
}


# Load --------------------------------------------------------------------


dt_members <- dt_dbReadTable(conn, "members")
dt_raceResults <- dt_dbReadTable(conn, "raceResults")

dt_twintownMeberships <- dt_dbReadTable(conn, "twintownMemberships")


# options -----------------------------------------------------------------

n_races_recent <- 6

# n_months_recent <- 12 #how far back to check for race results
n_weeks_soon <- 6

date_today <- dt_twintownMeberships$date_updated |> max() |> ymd()
# date_cutoff <- date_today - months(n_months_recent)
# date_cutoff_char <- date_cutoff |> format("%Y-%m-%d")

date_cutoff <- dt_raceResults[
  date_ymd < date_today,
  .(date_cutoff = date_ymd |> unique() |> sort(decreasing = TRUE) |> (function(x) x[n_races_recent])())]$date_cutoff


date_soon <- date_today + weeks(n_weeks_soon)
date_soon_char <- date_soon |> format("%Y-%m-%d")

date_membershipEarliest <- dt_twintownMeberships$date_updated |> min() |> ymd()


```

```{r}
# Prep --------------------------------------------------------------------


dt_twintownMeberships[, is_latest := date_updated == max(date_updated), by = .(twintownsMembershipID)]

dt_twintownMebershipsLatest <- dt_twintownMeberships[(is_latest)]

# check who's raced in period
dt_raceResultsRecent <- dt_raceResults[date_ymd >= date_cutoff]

dt_membersRecent <- dt_raceResultsRecent[,.
                                         (n_races = .N,
                                           date_last_race = max(date_ymd)),
                                         by = .(id_member)]

dt_membersRecent[dt_members,
                 on = .(id_member),
                 `:=`(
                   name_display = i.name_display,
                   twintownsMembershipID = i.twintownsMembershipID,
                   name_last = i.name_last,
                   name_first = i.name_first
                 )]

dt_membersRecent[dt_twintownMebershipsLatest,
                 on = .(twintownsMembershipID),
                 `:=`(
                   date_dueTriathlon = i.date_dueTriathlon,
                   date_dueMain = i.date_dueMain,
                   email = i.email,
                   phoneMobile = i.phoneMobile
                 )]

# # count number of races in period
# dt_membersRecent <- dt_members[
#   id_member %in% dt_raceResults[date_ymd >= date_cutoff_char]$id_member,
#   .(name_display,twintownsMembershipID, name_last)
#   ]

dt_membersRecent[, is_current := !is.na(date_dueTriathlon) & date_dueTriathlon >= date_today & date_dueMain > date_today]
dt_membersRecent[, is_dueSoon := !is.na(date_dueTriathlon) & (is_current) & (date_dueTriathlon < date_soon_char | date_dueMain < date_soon_char) ]

setorder(dt_membersRecent, name_last, name_first)

```

# Membership status - as of `r toNiceDate(date_today)` 

For all racers in last `r n_races_recent` races (since `r toNiceDate(date_cutoff)`).

<!-- Those without a TwinTowns ID have no membership recorded since at least `r toNiceDate(date_membershipEarliest)`. -->


```{r}
dt_none <- dt_membersRecent[
  !(is_current)][
    # order(-n_races, -date_last_race)][
      , .(Name = name_display,
          # ID = ifelse(is.na(twintownsMembershipID), "", twintownsMembershipID),
          # n_races,
          `Latest race` = date_last_race,
          `Tri club due` = ifelse(is.na(date_dueTriathlon), "", date_dueTriathlon)#,
          #`Main club due` = ifelse(is.na(date_dueMain), "", date_dueMain
          # )
      )
    ]

dt_none[`Tri club due`=="", `Tri club due` := "NO MEMBERSHIP"]
# setnames(dt_none, "n_races", glue("Races in {n_months_recent} months", n_months_recent = n_months_recent))

# knitr::kable(dt_none)
```

## Has raced without a membership

```{r}
dt_none[`Latest race`> `Tri club due` | `Tri club due` == "NO MEMBERSHIP"] |> kable()
```

## Membership expired but haven't raced since
```{r}
dt_none[`Latest race`< `Tri club due` & !(`Tri club due` == "NO MEMBERSHIP")] |> kable()
```


## Expiring Soon (before `r toNiceDate(date_soon)`)

```{r}
dt_soon <- dt_membersRecent[
  (is_dueSoon)][
    order(-n_races, -date_last_race)][
      , .(Name = name_display,
          # ID = ifelse(is.na(twintownsMembershipID), "", twintownsMembershipID),
          # n_races,
          `Latest race` = date_last_race,
          `Tri club due` = ifelse(is.na(date_dueTriathlon), "", date_dueTriathlon)
          # `Main club due` = ifelse(is.na(date_dueMain), "", date_dueMain)
      )
    ]

# setnames(dt_soon, "n_races", glue("Races in {n_months_recent} months", n_months_recent = n_months_recent))

knitr::kable(dt_soon)
```


<!-- ::: -->